version: 0.0
os: linux


files:
 - source: ./
   destination: /opt/buznear/stg-buznear
   overwrite: yes
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: scripts/status.sh
      timeout: 180
      runas: root
